// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZbdLmbvGjrvE97xK11bTHm8pCNdYitgQ',
    appId: '1:416395897630:web:be2fd35e3dcdd9ff0b770f',
    messagingSenderId: '416395897630',
    projectId: 'e-pharmacy-e65d1',
    authDomain: 'e-pharmacy-e65d1.firebaseapp.com',
    storageBucket: 'e-pharmacy-e65d1.firebasestorage.app',
    measurementId: 'G-77EP5FM1MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRSsMNb3qCAKfFSCHTPHuoQV0HAPuD5Hk',
    appId: '1:416395897630:android:50f94b3e7a9f22d00b770f',
    messagingSenderId: '416395897630',
    projectId: 'e-pharmacy-e65d1',
    storageBucket: 'e-pharmacy-e65d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATojondj3kmea4mQm-utMPE28tCypTub0',
    appId: '1:416395897630:ios:90a4867c278ad09f0b770f',
    messagingSenderId: '416395897630',
    projectId: 'e-pharmacy-e65d1',
    storageBucket: 'e-pharmacy-e65d1.firebasestorage.app',
    iosBundleId: 'com.example.ePharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATojondj3kmea4mQm-utMPE28tCypTub0',
    appId: '1:416395897630:ios:90a4867c278ad09f0b770f',
    messagingSenderId: '416395897630',
    projectId: 'e-pharmacy-e65d1',
    storageBucket: 'e-pharmacy-e65d1.firebasestorage.app',
    iosBundleId: 'com.example.ePharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZbdLmbvGjrvE97xK11bTHm8pCNdYitgQ',
    appId: '1:416395897630:web:ca7c9b4a48c1ead20b770f',
    messagingSenderId: '416395897630',
    projectId: 'e-pharmacy-e65d1',
    authDomain: 'e-pharmacy-e65d1.firebaseapp.com',
    storageBucket: 'e-pharmacy-e65d1.firebasestorage.app',
    measurementId: 'G-X83Y01KNGE',
  );
}
